In [1]:
# Import
import tools.EnergyCell as ec
import tools.tool_data_analysis as tda
import pandapower.toolbox as tb
import pandapower as pp
import pandapower.networks as pn
import simbench as sb  
    
from pandapower.plotting.plotly import simple_plotly
from pandapower.plotting.plotly import pf_res_plotly

In [2]:
net = sb.get_simbench_net('1-LV-rural1--0-sw')

In [3]:
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,parallel,df,in_service,subnet,autoTap,autoTapSetp,substation,autoTapSide,max_loading_percent,voltLvl
0,MV1.101-LV1.101-Trafo 1,0.16 MVA 20/0.4 kV DOTE 160/20 SGB,42,3,0.16,20.0,0.4,4.0,1.46875,0.46,...,1,1.0,True,LV1.101,0,NaN,NaN,None,100.0,6

In [5]:
net.load

,name,bus,p_mw,q_mvar,const_z_percent,const_i_percent,sn_mva,scaling,in_service,type,max_p_mw,subnet,min_p_mw,min_q_mvar,max_q_mvar,profile,voltLvl
0,LV1.101 Load 1,9,0.006,0.002371,0.0,0.0,0.006452,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L2-A,7
1,LV1.101 Load 2,7,0.003,0.001186,0.0,0.0,0.003226,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,H0-C,7
2,LV1.101 Load 3,13,0.005,0.001976,0.0,0.0,0.005376,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L1-A,7
3,LV1.101 Load 4,12,0.002,0.000790,0.0,0.0,0.002151,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,H0-B,7
4,LV1.101 Load 5,8,0.004,0.001581,0.0,0.0,0.004301,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L2-A,7
5,LV1.101 Load 6,5,0.003,0.001186,0.0,0.0,0.003226,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L1-A,7
6,LV1.101 Load 7,2,0.008,0.003162,0.0,0.0,0.008602,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L1-A,7
7,LV1.101 Load 8,0,0.014,0.005533,0.0,0.0,0.015054,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L2-A,7
8,LV1.101 Load 9,6,0.003,0.001186,0.0,0.0,0.003226,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L2-A,7
9,LV1.101 Load 10,11,0.012,0.004743,0.0,0.0,0.012903,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L1-A,7
10,LV1.101 Load 11,10,0.002,0.000790,0.0,0.0,0.002151,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,H0-A,7
11,LV1.101 Load 12,1,0.004,0.001581,0.0,0.0,0.004301,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L1-A,7
12,LV1.101 Load 13,4,0.014,0.005533,0.0,0.0,0.015054,1.0,True,NaN,NaN,LV1.101,NaN,NaN,NaN,L2-A,7

In [7]:
24*13

312